openapi: '3.0.3'
info:
  title: Camaguru
  version: '1.0'
servers:
  - url: http://localhost:8000
paths:
  /img:
    get:
      summary: Get a list of images
      parameters:
        - name: filter
          in: query
          description: Filter the results based on specific fields and conditions
          required: false
          schema:
            type: object
            additionalProperties:
              type: string
          style: deepObject
        - name: sort
          in: query
          description: Sort the results by specified fields
          required: false
          schema:
            type: string
          example: "field1,-field2"
        - name: offset
          in: query
          description: Number of records to skip
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          description: Maximum number of records to return
          required: false
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of images
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Img'
        '400':
          description: Bad request
        '500':
          description: Internal server error
    post:
      summary: Create a new image
      requestBody:
        description: Image to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Img'
      security:
        - bearerAuth: []
      responses:
        '201':
          description: Image created successfully
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /img/{id}:
    get:
      summary: Get an image by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: An image
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Img'
        '400':
          description: Bad request
        '404':
          description: Image not found
        '500':
          description: Internal server error
    put:
      summary: Update an image by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: Image data to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Img'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Image updated successfully
        '400':
          description: Bad request
        '404':
          description: Image not found
        '500':
          description: Internal server error
    patch:
      summary: Partially update an image by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: Partial image data to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Img'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Image updated successfully
        '400':
          description: Bad request
        '404':
          description: Image not found
        '500':
          description: Internal server error
    delete:
      summary: Delete an image by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Image deleted successfully
        '400':
          description: Bad request
        '404':
          description: Image not found
        '500':
          description: Internal server error

components:
  schemas:
    Img:
      type: object
      properties:
        id:
          type: integer
        link:
          type: string
        user_id:
          type: integer
        created_at:
          type: string
          format: date-time
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT


