services:
  db:
    image: postgres:latest
    restart: always
    expose:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
  api:
    image: cosmtrek/air
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: db
      JWT_SECRET: $JWT_SECRET
      air_wd: "/app"
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  web:
    build:
      context: web
      dockerfile: Dockerfile.dev
    volumes:
      - ./web:/app
    ports:
      - "8080:8080"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
