services:
  api:
    image: cosmtrek/air
    environment:
      air_wd: "/app"
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
  web:
    build:
      context: web
      dockerfile: Dockerfile.dev
    volumes:
      - ./web:/app
    ports:
      - "8080:8080"
